import AppShell from "../components/AppShell";
import PageHeader from "../components/PageHeader";
import DataTable from "../components/DataTable";
import StatusBadge from "../components/StatusBadge";
import {
  transactions,
} from "../data/mockData";

export default function TransactionsPage() {
  return (
    <AppShell role="admin">

      <PageHeader
        eyebrow="BLOCKCHAIN ACTIVITY"
        title="Transactions"
        description="Static representation of blockchain events generated by FoodTrace."
      />

      <div className="stats-grid three">

        <div className="stat-card">

          <div className="stat-label">
            Total transactions
          </div>

          <div className="stat-value">
            1,842
          </div>

          <div className="stat-change">
            +126 this week
          </div>

        </div>

        <div className="stat-card">

          <div className="stat-label">
            Confirmed
          </div>

          <div className="stat-value">
            1,817
          </div>

          <div className="stat-change">
            98.6% success
          </div>

        </div>

        <div className="stat-card">

          <div className="stat-label">
            Network
          </div>

          <div className="stat-value">
            1337
          </div>

          <div className="stat-change">
            FoodTrace Local
          </div>

        </div>

      </div>

      <section className="panel">

        <DataTable
          columns={[
            {
              key: "hash",
              label: "Transaction hash",
              render: (row) => (
                <code>
                  {row.hash}
                </code>
              ),
            },

            {
              key: "event",
              label: "Event",
            },

            {
              key: "entity",
              label: "Entity",
            },

            {
              key: "actor",
              label: "Actor",
            },

            {
              key: "time",
              label: "Time",
            },

            {
              key: "status",
              label: "Status",
              render: (row) => (
                <StatusBadge tone="confirmed">
                  {row.status}
                </StatusBadge>
              ),
            },
          ]}
          rows={transactions}
        />

      </section>

    </AppShell>
  );
}